---
title: "Singular Value Decomposition"
layout: page
---

```{r options, echo=FALSE}
library(knitr)

```

## Singular Value Decomposition

In the previous section, we motivated dimension reduction and showed a transformation that permitted us to approximate the distance between two dimensional points with just one dimension. The singular value decomposition (SVD) is a generalization of the algorithm we used in the motivational section. As in the example, the SVD provides a transformation of the original data. This transformation has some very useful properties. 

The main result SVD provides is that we can write an $m \times n$, matrix $\mathbf{Y}$ as

$$\mathbf{U}^\top\mathbf{Y} = \mathbf{DV}^\top$$

With:

* $\mathbf{U}$ is an $m \times p$ orthogonal matrix
* $\mathbf{D}$ is an $p \times p$ diagonal matrix
* $\mathbf{V}$ is an $n \times p$ orthogonal matrix 
  $\mathbf{Y}$ is an $m \times n$ matrix
  
 
  
with $p=\mbox{min}(m,n)$. $\mathbf{U}^\top$ provides a rotation of our data $\mathbf{Y}$ that turns out to be very useful because the variability (sum of squares to be precise) of the columns of $\mathbf{U}^\top \mathbf{Y}=\mathbf{VD}$ are decreasing.

Because $\mathbf{U}$ is orthogonal, we can write the SVD like this:

$$\mathbf{Y} = \mathbf{UDV}^\top$$

In fact, this formula is much more commonly used. 

This transformation of $Y$ also results in a matrix with column of decreasing sum of squares.

In gene expression, n are the columns of the data matrix Y corresponding to assays and m are the rows corresponding to the genes. So U represents the variability in genes and V the variability in assays. The SVD of Y produces two orthonormal bases, one defined by right singular vectors and the other by left singular vectors. The right singular vectors define gene transcriptional responses {gi} and the left singular vectors define expression profiles {aj}. Following the convention of (Alter et al., 2000), we refer to the left singular vectors {uk} as eigenassays and to the right singular vectors {vk} as eigengenes where: 

$$g_i = \sum_{k=1}^{r} u_kd_kv_k, i:1,...,m$$

where the g_i is the i^{th} row of U

$$a_j = \sum_{k=1}^{r} v_{jk}d_ku_k, j:1...,n$$

where a_j is the j^{th} column of V^T

where U is an m x n matrix, S is an n x n diagonal matrix, and VT is also an n x n matrix. The columns of U are called the left singular vectors, {uk}, and form an orthonormal basis for the assay expression profiles, so that ui·uj = 1 for i = j, and ui·uj = 0 otherwise. The rows of VT contain the elements of the right singular vectors, {vk}, and form an orthonormal basis for the gene transcriptional responses. The elements of S are only nonzero on the diagonal, and are called the singular values. Thus, S = diag(s1,...,sn). Furthermore, sk > 0 for 1 ≤ k ≤ r, and sk = 0 for (r+1) ≤ k ≤ n. By convention, the ordering of the singular vectors is determined by high-to-low sorting of singular values, with the highest singular value in the upper left index of the S matrix. Note that for a square, symmetric matrix X, singular value decomposition is equivalent to diagonalization, or solution of the eigenvalue problem.

 
